version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'user1'
      MYSQL_PASSWORD: 'user1'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '33061:3306'
    expose:
      - 33061
    volumes:
      - my-db:/var/lib/mysql
  web:
    build: .
    restart: always
    ports:
      - "3443:3443"
    volumes:
      - ./:/usr/src/app
    environment:
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_HOST: 'db'
      # PORT IT'S OPTIONAL, IN THIS CASE IS COMMENT BECAUSE WE ARE CONNECTING IT WITH DOCKER NETWORK
      #MYSQL_PORT: '33061'
    links:
      - "db:database"
volumes:
  my-db:
    