version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - "3443:3443"
    volumes:
      - ./:/usr/src/app
    container_name: flask-app
    environment:
      MYSQL_DATABASE: 'db_test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user1'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PORT: '33061'
    depends_on:
      - db
    links:
      - db
    networks:
      - mysql-flask-app-network
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: 'db_test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user1'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33061:3306'
    expose:
      - 33061
    volumes:
      - my-db:/var/lib/mysql
  
    
networks:
  mysql-flask-app-network:
    name: mysql-flask-app-network
volumes:
  my-db:
    